### ISSUE TITLE
Link to example notebook for "generate yout own JSON" is broken

### ISSUE THREAD

**Issue by aflip** [poloclub/timbertrek#1]
Source URL: https://github.com/poloclub/timbertrek/blob/master/README.md 

> You can use the web demo to explore your own Rashomon Sets! You just need to choose the my own set tab below the tool and upload a JSON file containing all decision paths in your Rashomon Set.

> Check out this [example notebook](https://poloclub.github.io/timbertrek/notebook/retro/notebooks/?path=campas.ipynb) to see how to generate this JSON file. 

This link is broken. I liked the paper, and wanted to see if I could use my own data, but it is unclear how to do this. On the timbertek github.io page, in the widget that lets you pick your own data also, the link to how to do this is broken. it redirects to the readme and the link in the readme is broken.

Thank you

**Comment by xiaohk** [comment]
Hi @aflip, thank you so much for your interest! TimberTrek relies on the [TreeFAMRS (Trees FAst RashoMon Sets)](https://arxiv.org/abs/2209.08040) algorithm to generate the whole Rashomon set of decision tress. We are still polishing the APIs for TreeFARMS. We will update the TimberTrek example notebooks once we finalize the API (by mid October). I will ping you when it is done.

**Comment by xiaohk** [comment]
Hello @aflip and @robertfeldt, the TreeFARMS code is public now! https://github.com/ubc-systopia/treeFarms

You can install TreeFARMS with `pip install treefarms`. You can also checkout this [tutorial notebook](https://github.com/ubc-systopia/treeFarms/blob/main/treefarms/tutorial.ipynb). Let me know if you have any other question!

**Comment by robertfeldt** [comment]
Thanks for this. I have an up-to-date Python 3 version and updated pip but still no luck:

```
 % python3 --version
Python 3.10.8

 % pip3 install --upgrade pip
Requirement already satisfied: pip in /opt/homebrew/lib/python3.10/site-packages (22.2.2)

 % pip3 install treefarms
ERROR: Could not find a version that satisfies the requirement treefarms (from versions: none)
ERROR: No matching distribution found for treefarms
```

Ideas/help welcome, not sure what to do.

**Comment by robertfeldt** [comment]
I managed to build it on my machine and the example seems to work, so no problem (for now).

**Comment by xiaohk** [comment]
Glad you can build it on your machine. `pip install` should also work though. cc @zbw8388
