### ISSUE TITLE
Integration with Qualtrics?

### ISSUE THREAD

**Issue by lin-v-gan** [poloclub/timbertrek#3]
Hi there!  

Thank you once again for developing this amazing tool.  

Would it be possible to embed the interactive in a Qualtrics Survey?

Thanks!

**Comment by xiaohk** [comment]
Hello! Thanks for your kind words!

Yup, you can host your own TimberTrek somewhere (e.g., a GitHub page) and add an iframe element in your Qualtrics survey.

For example, to include our TimberTrek demo, you can write the following HTML code.

```html
<iframe
    srcdoc="https://poloclub.github.io/timbertrek/"
    frameBorder="0"
    width="100%"
    height="900px"
    id="timbertrek-iframe">
</iframe>
```

**Comment by lin-v-gan** [comment]
Thanks, @xiaohk !
